### ISSUE TITLE
App start looks strange v4.0

### ISSUE THREAD

**Issue by theChaosCoder** [stax76/MediaInfo.NET#1]
It looks like the width and height is set to 0.
Tested on win10 x64.

This is how it looks
![2019-10-22_17-24-09](https://user-images.githubusercontent.com/3579830/67302387-1bab0800-f4f1-11e9-92c6-b1e5231471ce.png)

**Comment by stax76** [comment]
The old settings are incompatible, I missed adding a migration. You can fix it by resizing the window and  then right-click and select settings, there you can paste the latest defaults:

```
font = consolas
font-size = 14
window-width = 750
window-height = 550
center-screen = yes
raw-view = yes
word-wrap = no
```

Or you can delete the conf file:

```PowerShell
Remove-Item C:\Users\*\AppData\Roaming\MediaInfo.NET\settings.conf
```

**Comment by theChaosCoder** [comment]
ahh works perfect now.
