### ISSUE TITLE
6.9.0.0: Multiple video streams are missing in summary

### ISSUE THREAD

**Issue by JJKylee** [stax76/MediaInfo.NET#10]
When there are multiple video streams, their info is missing in the summary.

See this:

![Mediainfo NET_6 9 0 0_video_streams_summary_missing_in_multiple_video_streams_20210314](https://user-images.githubusercontent.com/3157518/111078573-64cb7580-84b3-11eb-8b9d-7eee72638b10.jpg)

The sample video used in this: [here](https://we.tl/t-Sr7tLrHR8L).

**Comment by stax76** [comment]
Thanks for reporting JJKylee. I've uploaded a new release.
