### ISSUE TITLE
7.1.0.0: Reads hidden/non-media files in Previous/Next navigation

### ISSUE THREAD

**Issue by JJKylee** [stax76/MediaInfo.NET#11]
Hi, @stax76.

**MediaInfo.NET** seems to read _hidden_ files such as `desktop.ini`, `.DS_Store`, etc. along with _unassociated non-media files_ (`*.txt`, `*.pdf`, etc.) in Previous(`F11`)/Next(`F12`) navigation. Is this intended, or a bug? 🙄❓

![MediaInfo NET_7 1 0 0_reads_hidden_files_20210331](https://user-images.githubusercontent.com/3157518/113171668-8a1eea00-91fc-11eb-811f-0bfbac312b9b.gif)

**Comment by stax76** [comment]
Hello @JJKylee,
in the next release will be:

- Next/Previous uses only known media file types
- Larger list of known media file types
