### ISSUE TITLE
MKV container: No Attachments listed after add and save with Header Editor tool of MKVToolnix 

### ISSUE THREAD

**Issue by RobyOne77** [stax76/MediaInfo.NET#17]
Hi,

when I add or modify Attachments in mkv file, Mediainfo will not report  in general paragraph.

**Comment by JeromeMartinez** [comment]
This is a [MediaInfoLib](https://github.com/MediaArea/MediaInfoLib) (used by MediaInfo.NET) issue, not a MediaInfo.NET one.

**Comment by RobyOne77** [comment]
Thanks @JeromeMartinez. 
Closed
