### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by kchiem** [stax76/MediaInfo.NET#2]
> Install the .NET Core 3.0 Runtime.

Done.

> Run MediaInfo.NET and right-click to show the context menu, choose Install to register common file associations

How do I "Run MediaInfo.NET"?  When I double click on MediaInfoNET.exe, nothing happens?

**Comment by stax76** [comment]
Did you also install the Desktop Runtime?

https://dotnet.microsoft.com/download/dotnet-core/3.0/runtime

**Comment by kchiem** [comment]
Hi Frank,

No, I didn't.  Thanks, it works now!

PS.  Thanks for coming back to StaxRip!
