### ISSUE TITLE
Suggestions: compact summary in normal view, etc.

### ISSUE THREAD

**Issue by gnucian** [stax76/MediaInfo.NET#3]
1. Compact summary is enabled only in the raw view mode.
It'd be good if it is enabled in normal view as well.

2. There is only dark mode.
Light mode as an option would be good.

3. Internationalization of the UI would be good, too.
I'm willing to help you with my native language - Korean.

**Comment by stax76** [comment]
Thanks for the feedback!

> Compact summary is enabled only in the raw view mode.
> It'd be good if it is enabled in normal view as well.

I've implemented it today, it will be available shortly.

For the other two please create separate issues, both are large tasks, I'll be taking a break before I start anything large.

**Comment by gnucian** [comment]
I see.
Thanks a million.
