### ISSUE TITLE
6.0.0.0 fails to open files

### ISSUE THREAD

**Issue by gnucian** [stax76/MediaInfo.NET#7]
**[System]**
Windows : Windows 10 Home 2004
Language : English (United States)
CPU : Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
GPU : NVIDIA GeForce GTX 1060 with Max-Q Design, Intel(R) HD Graphics 630

6.0.0.0 cannot open any video file with the following error message.
On the other hand, 5.7.0.0 does not have any problem.

**[Error Message]**
[Here](https://pastebin.com/hnkgeZVe)

**Comment by stax76** [comment]
This error typically happens when a x64 process tries to load a x86 DLL, I'll examine it.

**Comment by gnucian** [comment]
I replaced the MediaInfo.dll file with the most recent x64 version.
Now 6.0.0.0 is working well.
I guess you mistakenly included the x32 version of MediaInfo.dll.

**Comment by stax76** [comment]
My bad, sorry. I searched MediaInfo.dll with Everything and a look in the size column shows the size of the DLL in the 6.0.0.0 release is the same as the size in the mpv.net x86 folder.

The reason why it was still working here is I have mpv.net in PATH which contains a x64 MediaInfo.dll and that's what the OS or the .NET Framework was using instead. The startup folder has a higher priority but if it contains a DLL that cannot be loaded then apparently the OS or the .NET Framework tries to find a working DLL somewhere else.

I try to quit PC for today, have a nice day, again sorry.

**Comment by gnucian** [comment]
Oh, it's totally OK. Never mind.
Thanks anyway.
