### ISSUE TITLE
Is there a cache of Get-MediaInfo.ps1 I could disable?

### ISSUE THREAD

**Issue by eugenesvk** [stax76/MediaInfo.NET#8]
I'm trying to edit Get-MediaInfo.ps1 to get the view that I like instead of the default
To have near-instant feedback I have a shortcut to launch MediaInfoNET.exe with some video file and do the following cycle:
1. I make edits to Get-MediaInfo.ps1 and save the result
2. I launche the shortcut mentioned above and press F9 to see the results of my edits
3. I close the folder view and MediaInfoNET.exe

GoTo 1.

However, I've noticed that there is some kind of cache or someting — the view doesn't get updated after Step1, to force an update I have to actually change the folder path where MediaInfoNET.exe is located.
Is there indeed some kind of cache in place that prevents and update of Get-MediaInfo.ps1 to be applied right away?
Is there a way to disable it?
Thanks!

**Comment by stax76** [comment]
Maybe just increase the value of the variable $CacheVersion, currently in line 6 it's:

$CacheVersion    = 43

This will rebuild the cache on the next run.

**Comment by stax76** [comment]
There is a better way. For each media file a cache file gets created in the users temp directory, the file extension is json, so you could delete all json files in your temp directory, following command does that:

`remove-item "$($env:temp)\*.json"`
